# Generated by Django 4.2.29 on 2026-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('approver', 'Approver'), ('lite_user', 'Lite User')], default='lite_user', max_length=20),
        ),
    ]
