# Generated by Django 4.2.7 on 2026-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_comment',
            field=models.BooleanField(default=False, verbose_name='Add Comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_member',
            field=models.BooleanField(default=False, verbose_name='Add Member'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_proof',
            field=models.BooleanField(default=False, verbose_name='Add Proof'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_folder',
            field=models.BooleanField(default=False, verbose_name='Create Folder'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_folder',
            field=models.BooleanField(default=False, verbose_name='Delete Folder'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_proof_in_folder',
            field=models.BooleanField(default=False, verbose_name='Delete Proof'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_proof_in_preview',
            field=models.BooleanField(default=False, verbose_name='Delete Proof'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_folder',
            field=models.BooleanField(default=False, verbose_name='Edit Folder'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_use_proofieplus',
            field=models.BooleanField(default=False, verbose_name='ProofiePlus'),
        ),
    ]
