# Generated by Django 4.2.7 on 2026-04-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_can_add_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_proof_in_folder',
            field=models.BooleanField(default=False, verbose_name='Inside Folder'),
        ),
    ]
