# Generated by Django 4.2.7 on 2026-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_permission_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_proof_in_folder',
            field=models.BooleanField(default=False, verbose_name='Add Proof'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_proof_in_folder',
            field=models.BooleanField(default=False, verbose_name='Delete Proof'),
        ),
    ]
