# Generated by Django 4.2.7 on 2026-04-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_add_proof_in_folder_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_make_decisions',
            field=models.BooleanField(default=False, verbose_name='Make Decisions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
