# Generated by Django 4.2.7 on 2026-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_can_make_decisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_proof',
            field=models.BooleanField(default=False, verbose_name='Create Proof'),
        ),
    ]
