# Generated by Django 4.2.7 on 2026-04-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_can_create_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_add_member',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_delete_member',
            field=models.BooleanField(default=False, verbose_name='Add/Delete Member'),
        ),
    ]
