# Generated by Django 4.2.7 on 2026-04-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_can_add_member_to_can_add_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_add_proof',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_delete_proof',
            field=models.BooleanField(default=False, verbose_name='Add/Delete Proof'),
        ),
    ]
