# Generated by Django 4.2.7 on 2026-04-06 06:24

from django.db import migrations


def populate_is_active_field(apps, schema_editor):
    """Populate UserProfile.is_active with User.is_active values"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    User = apps.get_model('auth', 'User')
    
    for profile in UserProfile.objects.all():
        if profile.user:
            profile.is_active = profile.user.is_active
            profile.save(update_fields=['is_active'])


def reverse_populate_is_active_field(apps, schema_editor):
    """Reverse operation - set is_active back to default True"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        profile.is_active = True
        profile.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_user_profile_is_active'),
    ]

    operations = [
        migrations.RunPython(populate_is_active_field, reverse_populate_is_active_field),
    ]
