# Generated by Django 4.2.7 on 2026-04-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('can_download', models.BooleanField(default=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_comment', models.BooleanField(default=False)),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma-separated list of allowed domains')),
                ('password', models.CharField(blank=True, help_text='Optional password protection', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='versioning.creativeasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='versioning__token_889a14_idx'), models.Index(fields=['expires_at', 'is_active'], name='versioning__expires_c2c0f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('edit', 'Edit'), ('comment', 'Comment')], max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='versioning.creativeasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'expires_at'], name='versioning__token_98842e_idx'), models.Index(fields=['user', 'purpose'], name='versioning__user_id_7b854f_idx')],
            },
        ),
    ]
