# Generated by Django 4.2.7 on 2026-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0002_assetsharetoken_assetaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeasset',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creativeasset',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
