# Generated by Django 4.2.7 on 2026-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0003_creativeasset_file_url_creativeasset_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='asset_file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='asset_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='asset_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
