# Generated by Django 4.2.7 on 2026-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0005_folder_project_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
