# Generated by Django 4.2.7 on 2026-04-04 12:12

from django.db import migrations


def create_owner_memberships(apps, schema_editor):
    """Create FolderMember entries for all existing folder owners"""
    Folder = apps.get_model('versioning', 'Folder')
    FolderMember = apps.get_model('versioning', 'FolderMember')
    
    for folder in Folder.objects.all():
        # Create owner membership if it doesn't exist
        FolderMember.objects.get_or_create(
            folder=folder,
            user=folder.owner,
            defaults={
                'role': 'owner',
                'added_by': folder.owner
            }
        )


def reverse_owner_memberships(apps, schema_editor):
    """Remove owner memberships (reverse migration)"""
    FolderMember = apps.get_model('versioning', 'FolderMember')
    FolderMember.objects.filter(role='owner').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0007_foldermember'),
    ]

    operations = [
        migrations.RunPython(create_owner_memberships, reverse_owner_memberships),
    ]
