# Generated by Django 4.2.7 on 2026-04-06 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0008_auto_20260404_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='versioning.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='proof_family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='project',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
