# Generated by Django 4.2.7 on 2026-04-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0009_add_versioning_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parent_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='proof_family_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version_number',
        ),
    ]
