# Generated by Django 4.2.7 on 2026-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0010_remove_proof_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
