# Generated by Django 4.2.7 on 2026-04-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0009_project_workflow_stage_reviewers_and_more'),
        ('versioning', '0011_add_version_number_field'),
    ]

    operations = [
    ]
