# Generated by Django 4.2.29 on 2026-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0011_add_version_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow_stage_reviewers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
