# Generated by Django 4.2.29 on 2026-03-30 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcycle',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('approved_with_changes', 'Approved with Changes'), ('rejected', 'Rejected')], default='not_started', max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('group_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_with_changes', 'Approved with Changes'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('socd_status', models.CharField(choices=[('sent', 'Sent'), ('open', 'Open'), ('commented', 'Comment Made'), ('decision_made', 'Decision Made')], default='sent', max_length=20)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='workflows.reviewcycle')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('review_cycle', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socd_status', models.CharField(choices=[('sent', 'Sent'), ('open', 'Open'), ('commented', 'Comment Made'), ('decision_made', 'Decision Made')], default='sent', max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('commented_at', models.DateTimeField(blank=True, null=True)),
                ('decision_made_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workflows.approvalgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
