# Generated by Django 4.2.29 on 2026-03-30 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0002_alter_reviewcycle_status_approvalgroup_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcycle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
