# Generated by Django 4.2.7 on 2026-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_reviewcycle_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageapproval',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stageapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('approver__isnull', False)), fields=('review_cycle', 'stage', 'approver'), name='unique_stage_approval_with_approver'),
        ),
    ]
