# Generated by Django 4.2.7 on 2026-04-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_stageapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
