# Generated by Django 4.2.7 on 2026-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_add_is_default_to_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('approver', 'Approver'), ('lite_user', 'Lite User')], max_length=20, unique=True, verbose_name='Role')),
                ('can_create_folder', models.BooleanField(default=False, verbose_name='Create Folder')),
                ('can_add_member', models.BooleanField(default=False, verbose_name='Add Member')),
                ('can_edit_folder', models.BooleanField(default=False, verbose_name='Edit Folder')),
                ('can_add_proof', models.BooleanField(default=False, verbose_name='Add Proof')),
                ('can_delete_folder', models.BooleanField(default=False, verbose_name='Delete Folder')),
                ('can_delete_proof_in_folder', models.BooleanField(default=False, verbose_name='Delete Proof')),
                ('can_use_proofieplus', models.BooleanField(default=False, verbose_name='ProofiePlus')),
                ('can_add_comment', models.BooleanField(default=False, verbose_name='Add Comment')),
                ('can_delete_proof_in_preview', models.BooleanField(default=False, verbose_name='Delete Proof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role'],
            },
        ),
    ]
