# Generated by Django 4.2.7 on 2026-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_make_decisions',
            field=models.BooleanField(default=False, verbose_name='Make Decisions'),
        ),
    ]
