# Generated by Django 4.2.7 on 2026-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_rolepermission_can_make_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_create_proof',
            field=models.BooleanField(default=False, verbose_name='Create Proof'),
        ),
    ]
