# Generated by Django 4.2.29 on 2026-04-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_rolepermission_can_create_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalgroup',
            name='stage_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('approved_with_changes', 'Approved with Changes'), ('rejected', 'Rejected'), ('action_required', 'Action Required')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='reviewer_progress',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('approved_with_changes', 'Approved with Changes'), ('rejected', 'Rejected')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='proof_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('approved_with_changes', 'Approved with Changes'), ('rejected', 'Rejected')], default='not_started', max_length=30),
        ),
    ]
