# Generated by Django 4.2.7 on 2026-04-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0009_add_reviewer_workflow_proof_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('comment', 'Comment Added'), ('decision', 'Decision Made')], max_length=20)),
                ('content', models.TextField(help_text='Formatted activity description')),
                ('metadata', models.JSONField(default=dict, help_text='Store decision type, comment text, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflows.reviewcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['review_cycle', 'timestamp'], name='workflows_a_review__7d2f91_idx'), models.Index(fields=['user', 'timestamp'], name='workflows_a_user_id_47b9b7_idx')],
            },
        ),
    ]
