# Generated by Django 4.2.7 on 2026-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('comment', 'Comment Added'), ('comment_deleted', 'Comment Deleted'), ('decision', 'Decision Made')], max_length=20),
        ),
    ]
