# Generated by Django 4.2.29 on 2026-04-11 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versioning', '0006_add_project_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_summary', models.JSONField()),
                ('changes_count', models.IntegerField(default=0)),
                ('pages_affected', models.JSONField(default=list)),
                ('severity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('as_is_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_is_diffs', to='versioning.fileversion')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_be_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_be_diffs', to='versioning.fileversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('as_is_version', 'to_be_version')},
            },
        ),
        migrations.CreateModel(
            name='TestCaseGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_cases', models.JSONField()),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='test_cases/%Y/%m/%d/')),
                ('jira_attachment_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diff_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='ai_engine.diffanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JIRAIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi_id', models.CharField(db_index=True, max_length=100)),
                ('jira_ticket_key', models.CharField(max_length=50)),
                ('jira_comment_id', models.CharField(blank=True, max_length=100)),
                ('summary_posted', models.BooleanField(default=False)),
                ('test_cases_attached', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_integrations', to='versioning.creativeasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cpi_id'], name='ai_engine_j_cpi_id_45bad5_idx'), models.Index(fields=['jira_ticket_key'], name='ai_engine_j_jira_ti_1e3a80_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('summary', 'Document Summary'), ('diff', 'Version Diff'), ('content_analysis', 'Content Analysis'), ('test_cases', 'Test Cases')], max_length=20)),
                ('result', models.JSONField()),
                ('cpi_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='versioning.creativeasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='versioning.fileversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'analysis_type'], name='ai_engine_a_asset_i_81010c_idx'), models.Index(fields=['cpi_id'], name='ai_engine_a_cpi_id_ba8f86_idx')],
            },
        ),
    ]
