# Generated by Django 4.2.30 on 2026-04-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0012_project_workflow_stage_reviewers_and_more'),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegeneration',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='versioning.fileversion'),
        ),
        migrations.AlterField(
            model_name='testcasegeneration',
            name='diff_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='ai_engine.diffanalysis'),
        ),
    ]
