import logging
from django.conf import settings
from jira import JIRA
from jira.exceptions import JIRAError

logger = logging.getLogger(__name__)


class JIRAService:
    def __init__(self):
        self.server = getattr(settings, 'JIRA_SERVER', '')
        self.email = getattr(settings, 'JIRA_EMAIL', '')
        self.api_token = getattr(settings, 'JIRA_API_TOKEN', '')
        self.client = None
        
        if self.server and self.email and self.api_token:
            try:
                self.client = JIRA(
                    server=self.server,
                    basic_auth=(self.email, self.api_token)
                )
                logger.info(f"JIRA client initialized for {self.server}")
            except JIRAError as e:
                logger.error(f"Failed to initialize JIRA client: {e}")
        else:
            logger.warning("JIRA credentials not configured")
    
    def search_ticket_by_cpi(self, cpi_id):
        if not self.client:
            raise ValueError("JIRA client not initialized. Check credentials in .env")
        
        try:
            # Try multiple search strategies
            search_queries = [
                f'text ~ "{cpi_id}"',
                f'summary ~ "{cpi_id}"',
                f'description ~ "{cpi_id}"',
                f'text ~ "{cpi_id}" OR summary ~ "{cpi_id}" OR description ~ "{cpi_id}"',
                f'key = "{cpi_id}"',  # In case CPI-3632 is the actual ticket key
            ]
            
            for jql in search_queries:
                logger.info(f"Trying JIRA search with JQL: {jql}")
                try:
                    issues = self.client.search_issues(jql, maxResults=5)
                    logger.info(f"Search returned {len(issues)} results")
                    
                    if issues:
                        issue = issues[0]
                        logger.info(f"Found JIRA ticket: {issue.key} - {issue.fields.summary}")
                        return {
                            'key': issue.key,
                            'summary': issue.fields.summary,
                            'status': issue.fields.status.name,
                            'url': f"{self.server}/browse/{issue.key}"
                        }
                except JIRAError as search_error:
                    logger.warning(f"Search failed for JQL '{jql}': {search_error}")
                    continue
            
            logger.warning(f"No JIRA ticket found for CPI ID: {cpi_id} after trying all search strategies")
            return None
        except JIRAError as e:
            logger.error(f"Error searching JIRA: {e}")
            raise
    
    def post_comment(self, ticket_key, comment_text):
        if not self.client:
            raise ValueError("JIRA client not initialized")
        
        try:
            comment = self.client.add_comment(ticket_key, comment_text)
            logger.info(f"Posted comment to {ticket_key}")
            return {
                'id': comment.id,
                'url': f"{self.server}/browse/{ticket_key}?focusedCommentId={comment.id}"
            }
        except JIRAError as e:
            logger.error(f"Error posting comment to JIRA: {e}")
            raise
    
    def format_summary_comment(self, summary_data, cpi_id=None):
        title = summary_data.get('title', 'Document Summary')
        doc_type = summary_data.get('type', 'N/A')
        complexity = summary_data.get('complexity', 'N/A')
        review_time = summary_data.get('estimated_review_time', 'N/A')
        highlights = summary_data.get('key_highlights', [])
        
        comment = f"*ProofiePlus AI - Document Summary*\n\n"
        
        if cpi_id:
            comment += f"*CPI ID:* {cpi_id}\n"
        
        comment += f"*Document:* {title}\n"
        comment += f"*Type:* {doc_type}\n"
        comment += f"*Complexity:* {complexity}\n"
        comment += f"*Estimated Review Time:* {review_time}\n\n"
        
        if highlights:
            comment += "*Key Highlights:*\n"
            for highlight in highlights:
                comment += f"* {highlight}\n"
        
        comment += "\n_Generated by ProofiePlus AI_"
        
        return comment
    
    def attach_file(self, ticket_key, file_path, filename=None):
        if not self.client:
            raise ValueError("JIRA client not initialized")
        
        try:
            with open(file_path, 'rb') as f:
                attachment = self.client.add_attachment(
                    issue=ticket_key,
                    attachment=f,
                    filename=filename
                )
            logger.info(f"Attached file to {ticket_key}: {filename}")
            return {
                'id': attachment.id,
                'filename': attachment.filename,
                'url': f"{self.server}/browse/{ticket_key}"
            }
        except Exception as e:
            logger.error(f"Error attaching file to JIRA: {e}")
            raise
