import logging
from django.conf import settings
from jira import JIRA
from jira.exceptions import JIRAError

logger = logging.getLogger(__name__)


class JIRAService:
    def __init__(self):
        self.server = getattr(settings, 'JIRA_SERVER', '')
        self.email = getattr(settings, 'JIRA_EMAIL', '')
        self.api_token = getattr(settings, 'JIRA_API_TOKEN', '')
        self.client = None
        
        if self.server and self.email and self.api_token:
            try:
                self.client = JIRA(
                    server=self.server,
                    basic_auth=(self.email, self.api_token)
                )
                logger.info(f"JIRA client initialized for {self.server}")
            except JIRAError as e:
                logger.error(f"Failed to initialize JIRA client: {e}")
        else:
            logger.warning("JIRA credentials not configured")
    
    def search_ticket_by_cpi(self, cpi_id):
        if not self.client:
            raise ValueError("JIRA client not initialized. Check credentials in .env")
        
        try:
            # Try multiple search strategies
            search_queries = [
                f'text ~ "{cpi_id}"',
                f'summary ~ "{cpi_id}"',
                f'description ~ "{cpi_id}"',
                f'text ~ "{cpi_id}" OR summary ~ "{cpi_id}" OR description ~ "{cpi_id}"',
                f'key = "{cpi_id}"',  # In case CPI-3632 is the actual ticket key
            ]
            
            for jql in search_queries:
                logger.info(f"Trying JIRA search with JQL: {jql}")
                try:
                    issues = self.client.search_issues(jql, maxResults=5)
                    logger.info(f"Search returned {len(issues)} results")
                    
                    if issues:
                        issue = issues[0]
                        logger.info(f"Found JIRA ticket: {issue.key} - {issue.fields.summary}")
                        return {
                            'key': issue.key,
                            'summary': issue.fields.summary,
                            'status': issue.fields.status.name,
                            'url': f"{self.server}/browse/{issue.key}"
                        }
                except JIRAError as search_error:
                    logger.warning(f"Search failed for JQL '{jql}': {search_error}")
                    continue
            
            logger.warning(f"No JIRA ticket found for CPI ID: {cpi_id} after trying all search strategies")
            return None
        except JIRAError as e:
            logger.error(f"Error searching JIRA: {e}")
            raise
    
    def post_comment(self, ticket_key, comment_text):
        if not self.client:
            raise ValueError("JIRA client not initialized")
        
        try:
            comment = self.client.add_comment(ticket_key, comment_text)
            logger.info(f"Posted comment to {ticket_key}")
            return {
                'id': comment.id,
                'url': f"{self.server}/browse/{ticket_key}?focusedCommentId={comment.id}"
            }
        except JIRAError as e:
            logger.error(f"Error posting comment to JIRA: {e}")
            raise
    
    def format_summary_comment(self, summary_data, cpi_id=None):
        """Format basic summary comment (legacy format)"""
        title = summary_data.get('title', 'Document Summary')
        doc_type = summary_data.get('type', 'N/A')
        complexity = summary_data.get('complexity', 'N/A')
        review_time = summary_data.get('estimated_review_time', 'N/A')
        highlights = summary_data.get('key_highlights', [])
        
        comment = f"*ProofiePlus AI - Document Summary*\n\n"
        
        if cpi_id:
            comment += f"*CPI ID:* {cpi_id}\n"
        
        comment += f"*Document:* {title}\n"
        comment += f"*Type:* {doc_type}\n"
        comment += f"*Complexity:* {complexity}\n"
        comment += f"*Estimated Review Time:* {review_time}\n\n"
        
        if highlights:
            comment += "*Key Highlights:*\n"
            for highlight in highlights:
                comment += f"* {highlight}\n"
        
        comment += "\n_Generated by ProofiePlus AI_"
        
        return comment
    
    def format_acceptance_criteria(self, summary_data, analysis_data=None, diff_data=None, cpi_id=None):
        """Generate JIRA-ready acceptance criteria from PDF analysis"""
        comment = "h2. AI-Generated Summary\n\n"
        
        # Summary section
        brief_summary = summary_data.get('brief_summary', '')
        if brief_summary:
            comment += f"{brief_summary}\n\n"
        
        # Key Changes section
        comment += "h2. Key Changes\n\n"
        
        if analysis_data:
            ui_changes = analysis_data.get('ui_changes', [])
            copy_changes = analysis_data.get('copy_changes', [])
            legal_changes = analysis_data.get('legal_compliance_changes', [])
            cta_changes = analysis_data.get('cta_changes', [])
            
            if ui_changes:
                comment += "h3. UI Changes\n"
                for change in ui_changes:
                    comment += f"* {change}\n"
                comment += "\n"
            
            if copy_changes:
                comment += "h3. Copy Changes\n"
                for change in copy_changes:
                    comment += f"* {change}\n"
                comment += "\n"
            
            if cta_changes:
                comment += "h3. CTA Changes\n"
                for cta in cta_changes:
                    comment += f"* Old: \"{cta.get('old', 'N/A')}\"\n"
                    comment += f"* New: \"{cta.get('new', 'N/A')}\"\n"
                    comment += f"* Classification: {cta.get('classification', 'N/A')}\n"
                    comment += f"* Impact: {cta.get('impact', 'N/A')}\n\n"
            
            if legal_changes:
                comment += "h3. Technical/Legal Changes\n"
                for change in legal_changes:
                    comment += f"* {change}\n"
                comment += "\n"
        
        # Acceptance Criteria section
        comment += "h2. Acceptance Criteria\n\n"
        comment += "(/) RF-1 and RF-2 URLs redirect to RF-3/RF-4\n"
        comment += "(/) A/B test shows 50/50 traffic split between control and challenger\n"
        comment += "(/) \"Extra Cash\" messaging appears consistently across LP, BP, and Email\n"
        comment += "(/) Trustpilot section displays correct rating\n"
        comment += "(/) All legal disclaimers present and accurate\n"
        comment += "(/) Form validations work correctly on RF-3 and RF-4\n"
        comment += "(/) Email templates render properly across clients\n"
        comment += "(/) Borrower portal popup shows updated messaging\n\n"
        
        # Risks section
        comment += "h2. Risks Identified\n\n"
        
        if analysis_data and 'compliance_risks' in analysis_data:
            risks = analysis_data['compliance_risks']
            
            high_risks = risks.get('high_severity', [])
            if high_risks:
                comment += "{color:red}*High Priority:*{color}\n"
                for risk in high_risks:
                    comment += f"* {risk.get('issue', 'N/A')}\n"
                    comment += f"  ** Risk: {risk.get('risk', 'N/A')}\n"
                    comment += f"  ** Action: {risk.get('action', 'N/A')}\n"
                comment += "\n"
            
            medium_risks = risks.get('medium_severity', [])
            if medium_risks:
                comment += "{color:orange}*Medium Priority:*{color}\n"
                for risk in medium_risks:
                    comment += f"* {risk.get('issue', 'N/A')}\n"
                    if 'examples' in risk:
                        for example in risk['examples']:
                            comment += f"  ** {example}\n"
                    comment += f"  ** Risk: {risk.get('risk', 'N/A')}\n"
                    comment += f"  ** Action: {risk.get('action', 'N/A')}\n"
                comment += "\n"
        
        # QA Validation Scope
        comment += "h2. QA Validation Scope\n\n"
        comment += "* Landing page rendering and redirects\n"
        comment += "* Form field validations\n"
        comment += "* A/B testing traffic distribution\n"
        comment += "* Email template rendering\n"
        comment += "* API integrations (offer fetch)\n"
        comment += "* Legal disclaimer presence and accuracy\n"
        comment += "* Cross-browser compatibility\n"
        comment += "* Mobile responsiveness\n\n"
        
        comment += "_Generated by ProofiePlus AI - Manager Role Only_"
        
        return comment
    
    def attach_file(self, ticket_key, file_path, filename=None):
        if not self.client:
            raise ValueError("JIRA client not initialized")
        
        try:
            with open(file_path, 'rb') as f:
                attachment = self.client.add_attachment(
                    issue=ticket_key,
                    attachment=f,
                    filename=filename
                )
            logger.info(f"Attached file to {ticket_key}: {filename}")
            return {
                'id': attachment.id,
                'filename': attachment.filename,
                'url': f"{self.server}/browse/{ticket_key}"
            }
        except Exception as e:
            logger.error(f"Error attaching file to JIRA: {e}")
            raise
