# Generated by Django 4.2.29 on 2026-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_added', 'Comment Added'), ('annotation_created', 'Annotation Created'), ('stage_approved', 'Stage Approved'), ('stage_rejected', 'Stage Rejected'), ('changes_requested', 'Changes Requested'), ('review_completed', 'Review Completed'), ('mentioned', 'Mentioned'), ('version_uploaded', 'Version Uploaded'), ('new_proof_assigned', 'New Proof Assigned')], max_length=50),
        ),
    ]
